# Generated by Django 3.2.7 on 2021-11-23 22:10

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(db_column='NOME', max_length=30)),
                ('cpf', models.CharField(db_column='TIPO', max_length=20)),
                ('sexo', models.CharField(db_column='SEXO', max_length=6)),
                ('idade', models.CharField(db_column='IDADE', max_length=3)),
                ('telefone', models.CharField(db_column='TELEFONE', max_length=11)),
                ('email', models.EmailField(db_column='EMAIL', max_length=30)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
