# Generated by Django 3.2.7 on 2021-11-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientemodel',
            name='idade',
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='cpf',
            field=models.CharField(db_column='CPF', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='email',
            field=models.EmailField(db_column='EMAIL', max_length=150),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='nome',
            field=models.CharField(db_column='NOME', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='sexo',
            field=models.CharField(db_column='SEXO', max_length=7),
        ),
    ]
