# Generated by Django 3.2.7 on 2021-12-01 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicomodel',
            options={'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
        migrations.AlterField(
            model_name='historicomodel',
            name='animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animalmodel'),
        ),
        migrations.AlterModelTable(
            name='historicomodel',
            table='HISTORICO',
        ),
    ]
